---
name: Update data
on:
  schedule:
    - cron: "5 17,20,23 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: starsep/osm-wtp
          path: osm-wtp
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: starsep/osm-wtp-compare
          path: osm-wtp-compare
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
          cache: 'pip'
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_ENV
        shell: bash
      - name: Cache WTP data
        id: cache-wtp
        uses: actions/cache@v3
        with:
          path: osm-wtp-compare/cache/wtp
          key: ${{ env.date }}
      - name: install dependencies and run
        run: |
          cd osm-wtp-compare
          pip install -r requirements.txt
          python main.py
      - name: commit and push update
        run: |
          cd osm-wtp
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add index.html
          git commit -m "Update ${{ env.date }}"
          git push origin main
